version: '3'

services:
  app:
    build:
      context: .
    container_name: testcontainers-demo
    depends_on:
      - db
    ports:
      - '8888:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=docker'

  db:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}